import type { DataTypeDefXsd } from '../types/aas';

// All 31 XSD data types from AAS V3.1 metamodel
export const ALL_XSD_TYPES: DataTypeDefXsd[] = [
  'xs:string',
  'xs:boolean',
  'xs:decimal',
  'xs:integer',
  'xs:double',
  'xs:float',
  'xs:date',
  'xs:time',
  'xs:dateTime',
  'xs:duration',
  'xs:int',
  'xs:long',
  'xs:short',
  'xs:byte',
  'xs:unsignedInt',
  'xs:unsignedLong',
  'xs:unsignedShort',
  'xs:unsignedByte',
  'xs:positiveInteger',
  'xs:nonNegativeInteger',
  'xs:negativeInteger',
  'xs:nonPositiveInteger',
  'xs:anyURI',
  'xs:base64Binary',
  'xs:hexBinary',
  'xs:gDay',
  'xs:gMonth',
  'xs:gMonthDay',
  'xs:gYear',
  'xs:gYearMonth',
] as DataTypeDefXsd[];

// All KeyTypes from AAS V3.1 metamodel
export const ALL_KEY_TYPES = [
  'GlobalReference',
  'FragmentReference',
  'AssetAdministrationShell',
  'Submodel',
  'SubmodelElement',
  'ConceptDescription',
  'Property',
  'MultiLanguageProperty',
  'Range',
  'Blob',
  'File',
  'ReferenceElement',
  'SubmodelElementCollection',
  'SubmodelElementList',
  'Entity',
  'RelationshipElement',
  'AnnotatedRelationshipElement',
  'Operation',
  'Capability',
  'BasicEventElement',
  'DataElement',
  'EventElement',
];

// All SubmodelElement type names
export const ALL_ELEMENT_TYPES = [
  'SubmodelElement',
  'Property',
  'MultiLanguageProperty',
  'Range',
  'SubmodelElementCollection',
  'SubmodelElementList',
  'File',
  'Blob',
  'ReferenceElement',
  'Entity',
  'RelationshipElement',
  'AnnotatedRelationshipElement',
  'Operation',
  'Capability',
  'BasicEventElement',
];
